/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRefreshRouteImport } from './routes/admin.refresh'
import { Route as ApiPublicAdminSeedShopRouteImport } from './routes/api.public.admin.seed-shop'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRefreshRoute = AdminRefreshRouteImport.update({
  id: '/admin/refresh',
  path: '/admin/refresh',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAdminSeedShopRoute = ApiPublicAdminSeedShopRouteImport.update({
  id: '/api/public/admin/seed-shop',
  path: '/api/public/admin/seed-shop',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin/refresh': typeof AdminRefreshRoute
  '/api/public/admin/seed-shop': typeof ApiPublicAdminSeedShopRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/refresh': typeof AdminRefreshRoute
  '/api/public/admin/seed-shop': typeof ApiPublicAdminSeedShopRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin/refresh': typeof AdminRefreshRoute
  '/api/public/admin/seed-shop': typeof ApiPublicAdminSeedShopRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/admin/refresh' | '/api/public/admin/seed-shop'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/admin/refresh' | '/api/public/admin/seed-shop'
  id: '__root__' | '/' | '/admin/refresh' | '/api/public/admin/seed-shop'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRefreshRoute: typeof AdminRefreshRoute
  ApiPublicAdminSeedShopRoute: typeof ApiPublicAdminSeedShopRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/refresh': {
      id: '/admin/refresh'
      path: '/admin/refresh'
      fullPath: '/admin/refresh'
      preLoaderRoute: typeof AdminRefreshRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/admin/seed-shop': {
      id: '/api/public/admin/seed-shop'
      path: '/api/public/admin/seed-shop'
      fullPath: '/api/public/admin/seed-shop'
      preLoaderRoute: typeof ApiPublicAdminSeedShopRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRefreshRoute: AdminRefreshRoute,
  ApiPublicAdminSeedShopRoute: ApiPublicAdminSeedShopRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
